//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> Director { get; set; }
        public Nullable<System.Guid> Basado { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.Guid> Nacionalidad { get; set; }
        public string Comentarios { get; set; }
        public string Genero { get; set; }
    }
}
